// Reconstructs the exact screenData payload the DAK web app sends.
// OutSystems validates the shape strictly: every screen variable must be present,
// including the EmptyListItem "type template" on each list. Omit one and the
// server answers 400 "Failed to parse JSON request content."

const filterList = () => ({
  List: [],
  EmptyListItem: {
    Naam: '', IsGeselecteerd: false, Id: '0', Categorie: '',
    Aantal: 0, IsVisible: true, IsEmptyValue: false,
  },
});

const filterSet = () => ({
  Woonplaatsen: filterList(),
  Eigenaren: filterList(),
  TypeWoning: filterList(),
  AantalKamers: filterList(),
  Aanbodmodel: filterList(),
  Doelgroep: filterList(),
  Voorzieningen: filterList(),
  Contractvormen: filterList(),
  Toegankelijkheid: filterList(),
  OnzichtbareFilters: filterList(),
  MaxPrijs: 0,
  MinPrijs: 0,
  Sortering: 0,
  SorteringIsAscending: false,
});

const publicatieList = () => ({
  List: [],
  EmptyListItem: {
    Id: '0',
    EinddatumTijd: '1900-01-01T00:00:00',
    PublicatieModel: '',
    PublicatieModule: '',
    PublicatieDatum: '1900-01-01T00:00:00',
    Matchpercentage: 0,
    VoorlopigePositie: '0',
    Foto_Locatie: '',
    GepersonaliseerdeHuur: '0',
    Slaagkans: 0,
    IsCluster: false,
    EenheidSoort: '',
    Adres: {
      Straatnaam: '', Huisnummer: 0, Huisletter: '', HuisnummerToevoeging: '',
      Postcode: '', Woonplaats: '', Wijk: '', PublicatieId: '0',
    },
    Cluster: {
      Naam: '', DetailSoort: '', Doelgroep: '',
      PrijsMinBekend: false, PrijsMin: '0', PrijsMaxBekend: false, PrijsMax: '0',
      WoonOppervlakteMinBekend: false, WoonVertrekkenTotOppMin: 0,
      WoonOppervlakteMaxBekend: false, WoonVertrekkenTotOppMax: 0,
      AantalEenheden: 0, AantalKamersMin: 0, AantalKamersMax: 0,
      Lengtegraad: '0', Breedtegraad: '0',
      Toegankelijkheid: '', Toegankelijkheidstag: '',
      PublicatieId: '0', SoortBouw: '', Eigenaar: '',
    },
    Eenheid: {
      DetailSoort: '', Bestemming: '', AantalKamers: 0,
      TotaleOppervlakte: '0', WoonVertrekkenTotOpp: '0', Doelgroep: '',
      NettoHuurBekend: false, NettoHuur: '0',
      Lengtegraad: '0', Breedtegraad: '0',
      Toegankelijkheid: '', Toegankelijkheidstag: '',
      PublicatieId: '0', SoortBouw: '', EnergieLabel: '', EnergieIndex: 0,
      Eigenaar: '', BrutoHuurBekend: false, Brutohuur: '0', SubsidiabeleHuur: '0',
    },
    PublicatieLabel: '',
    IsBewaard: false,
    IsVerborgen: false,
    ContractVorm: '',
    PublicatieOmschrijving: { Id: '0', Tekst: null },
    AantalReactiesOpPublicatie: '0',
    HeeftGereageerd: false,
    IsIntrekkenReactieToegestaan: false,
    RedenNietIntrekkenReactie: '',
    PositieAanbiedingsproces: '',
    VirtuelePositie: 0,
    Opleverdatum: '1900-01-01T00:00:00',
    HeeftLift: false,
    Verdieping: '',
    IsMetGepersonaliseerdeHuur: false,
    Voorziening: '',
    AanbiedingProcesSoort: '',
    AantalEenhedenBeschikbaar: 0,
  },
});

export function buildScreenVariables() {
  return {
    ActiefTabblad: 0,
    Platform: '',
    PlatformVersie: '',
    AantalVerborgenWoningen: 0,
    AdvertentielijstContainerId: '',
    MapandFiltersContainerId: '',
    Filters: filterSet(),
    Filters_Basis: filterSet(),
    Filters_ChipList: {
      List: [],
      EmptyListItem: { Categorie: '', Label: '', IsGroen: false },
    },
    FilterMenu_Trigger: true,
    PublicatieLijst_Basis: publicatieList(),
    PublicatieLijst_Gefilterd: publicatieList(),
    PublicatieLijst_Aanbod: publicatieList(),
    PublicatieLijst_Loting: publicatieList(),
    PublicatieLijst_VrijeSector: publicatieList(),
    PublicatieLijst_MiddenHuur: publicatieList(),
    PublicatieLijst_ParkerenOverig: publicatieList(),
    PublicatieLijst_Koop: publicatieList(),
    PublicatieLijst_HasAanbod: true,
    PublicatieLijst_Base_TeWeinigAanbod: false,
    PublicatieLijst_VerborgenItems: 0,
    HuidigePublicatieId: '0',
    _huidigePublicatieIdInDataFetchStatus: 1,
    woonplaats: '', _woonplaatsInDataFetchStatus: 1,
    soort: '', _soortInDataFetchStatus: 1,
    type: '', _typeInDataFetchStatus: 1,
    kamers: '', _kamersInDataFetchStatus: 1,
    doelgroep: '', _doelgroepInDataFetchStatus: 1,
    contractvorm: '', _contractvormInDataFetchStatus: 1,
    toegankelijkheid: '', _toegankelijkheidInDataFetchStatus: 1,
    aanbieder: '', _aanbiederInDataFetchStatus: 1,
  };
}
